(() => {
'use strict';
const VERSION='SALON-TUTORIAL-R3-V1.1-20260828';
const KEY='dpro_tutorial_salon_v1_1';
const SAFE_QUERY='embed_demo=1';
const STEPS=[
{step:1,role:'CUSTOMER',route:'index.html?embed_demo=1',title:'製品紹介DEMOと予約状況を見る',copy:'個人の予約履歴を表示しない製品紹介モードで、まず予約状況の見え方を確認します。',primary:'#booking-list',fallback:'.container > h3.section-title:first-of-type'},
{step:2,role:'CUSTOMER',route:'index.html?embed_demo=1',title:'担当スタッフを選ぶ場所を確認',copy:'担当スタッフの選択欄を確認します。選択は画面内だけに留め、予約確定は行いません。',primary:'#select_staff',fallback:'select.input-box'},
{step:3,role:'CUSTOMER',route:'index.html?embed_demo=1',title:'予約日と空き時間の見方を確認',copy:'予約日と空き時間の表示を確認します。時間選択はできますが「予約を確定」は押しません。',primary:'#time-slots',fallback:'#select_date'},
{step:4,role:'STAFF',route:'staff.html?embed_demo=1',title:'スタッフ画面で次の予約を確認',copy:'製品紹介モードでは個人情報を伏せた状態で、次の予約の確認位置を見ます。',primary:'#next-booking-card',fallback:'.next-card'},
{step:5,role:'STAFF',route:'staff.html?embed_demo=1',title:'担当者別・日付別の確認方法を見る',copy:'担当者を選んで予約を絞り込む場所を確認します。スタッフ認証の自動実行はしません。',primary:'#staff-selector',fallback:'select'},
{step:6,role:'OWNER IPAD',route:'owner-ipad.html?embed_demo=1',title:'iPadで今日・次営業日・今後を把握',copy:'店頭iPadで「今日」「次営業日」「今後」の件数を一目で把握できる位置を確認します。',primary:'#today-count',fallback:'.summary-grid'},
{step:7,role:'OWNER IPAD',route:'owner-ipad.html?embed_demo=1',title:'iPadで予約一覧と日付移動を見る',copy:'予約一覧と日付移動を確認します。予約追加・削除・DEMO準備は行いません。',primary:'#booking-list',fallback:'main .panel .booking-list'},
{step:8,role:'OWNER PC',route:'owner.html?embed_demo=1',title:'オーナーPCの予約サマリーを見る',copy:'PC版で今日の予約サマリーを確認します。オーナーログインは自動実行しません。',primary:'#today-count',fallback:'.grid-summary'},
{step:9,role:'OWNER PC',route:'owner.html?embed_demo=1',title:'オーナーPCの予約一覧を見る',copy:'日付ごとの予約一覧を確認します。手動予約追加・削除はチュートリアル対象外です。',primary:'#booking-list',fallback:'main .panel .booking-list'},
{step:10,role:'OWNER PC',route:'owner.html?embed_demo=1',title:'今日やることを確認して完了',copy:'最後に「今日やること」を確認します。LINE送信・予約変更・リセットなどの業務操作は行わず完了します。',primary:'#todo-list',fallback:'aside .panel .todo-list'}
];
const q=id=>document.getElementById(id);
const frame=q('dpro-tutorial-frame'),launcher=q('dpro-tutorial-launcher'),card=q('dpro-tutorial-card'),highlight=q('dpro-target-highlight'),dock=q('dpro-dock'),finish=q('dpro-finish');
let state=loadState(),target=null,targetSelector='',resolveToken=0,drag=null,raf=0;
function defaultState(){return{version:VERSION,status:'idle',step:0,x:16,y:16,updatedAt:Date.now()}}
function loadState(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');if(x&&x.version===VERSION)return{...defaultState(),...x}}catch{}return defaultState()}
function saveState(patch={}){state={...state,...patch,version:VERSION,updatedAt:Date.now()};try{localStorage.setItem(KEY,JSON.stringify(state))}catch{}return state}
function current(){return STEPS[Math.max(0,Math.min(STEPS.length-1,state.step||0))]}
function sameSafeRoute(route){return typeof route==='string'&&route.includes(SAFE_QUERY)&&!/(admin|system-check)\.html/i.test(route)}
function setFrameRoute(route){if(!sameSafeRoute(route))throw new Error('Unsafe Tutorial route blocked');const now=(frame.getAttribute('src')||'').replace(/^\.\//,'');if(now!==route)frame.setAttribute('src',route);else resolveTargetSoon()}
function showLauncher(){launcher.style.display='grid';card.classList.remove('is-open');dock.classList.remove('is-visible');finish.classList.remove('is-visible');clearHighlight();const hasProgress=['running','closed'].includes(state.status)&&state.step>0;q('dpro-resume').style.display=hasProgress?'inline-flex':'none';q('dpro-replay').style.display=['complete','skipped'].includes(state.status)?'inline-flex':'none'}
function startAt(step=0){saveState({status:'running',step:Math.max(0,Math.min(STEPS.length-1,step))});launcher.style.display='none';finish.classList.remove('is-visible');dock.classList.remove('is-visible');card.classList.add('is-open');renderStep();requestAnimationFrame(()=>q('dpro-next')?.focus())}
function start(){saveState({...defaultState(),status:'running'});state=loadState();startAt(0)}
function resume(){startAt(state.step||0)}
function replay(){saveState({...defaultState(),status:'running'});state=loadState();startAt(0)}
function complete(skipped=false){saveState({status:skipped?'skipped':'complete',step:STEPS.length-1});card.classList.remove('is-open');dock.classList.remove('is-visible');clearHighlight();q('dpro-finish-copy').textContent=skipped?'チュートリアルをスキップしました。Replayで最初から再開できます。':'お客様・スタッフ・iPad・オーナーPCの予約共有フローを10ステップで確認しました。';finish.classList.add('is-visible');q('dpro-finish-replay')?.focus()}
function closeTutorial(){saveState({status:'closed'});card.classList.remove('is-open');clearHighlight();dock.classList.add('is-visible');dock.focus()}
function skip(){complete(true)}
function next(){if(state.step>=STEPS.length-1){complete(false);return}saveState({status:'running',step:state.step+1});renderStep();q('dpro-next')?.focus()}
function back(){if(state.step<=0)return;saveState({status:'running',step:state.step-1});renderStep();q('dpro-back')?.focus()}
function renderStep(){const s=current();q('dpro-step-no').textContent=`${s.step} / ${STEPS.length}`;q('dpro-role').textContent=s.role;q('dpro-step-title').textContent=s.title;q('dpro-step-copy').textContent=s.copy;q('dpro-back').disabled=state.step===0;q('dpro-next').textContent=state.step===STEPS.length-1?'完了':'次へ';q('dpro-target-status').className='dpro-target-status';q('dpro-target-status').textContent='対象を確認中…';applyCardPosition(state.x,state.y);setFrameRoute(s.route);resolveTargetSoon()}
function frameDoc(){try{return frame.contentDocument||frame.contentWindow?.document||null}catch{return null}}
function visible(el){if(!el)return false;const w=frame.contentWindow;const cs=w?.getComputedStyle(el);const r=el.getBoundingClientRect();return !!cs&&cs.display!=='none'&&cs.visibility!=='hidden'&&Number(cs.opacity||1)>0&&r.width>0&&r.height>0}
function findTargetIn(doc,primary,fallback){const p=doc?.querySelector(primary);if(visible(p))return{el:p,selector:primary,kind:'primary'};const f=doc?.querySelector(fallback);if(visible(f))return{el:f,selector:fallback,kind:'fallback'};return null}
function resolveTargetSoon(){const token=++resolveToken;target=null;targetSelector='';clearHighlight();let tries=0;const run=()=>{if(token!==resolveToken)return;const doc=frameDoc();const s=current();const found=doc?findTargetIn(doc,s.primary,s.fallback):null;if(found){target=found.el;targetSelector=found.selector;try{target.scrollIntoView({block:'center',inline:'center',behavior:'auto'});if(!target.matches('button,input,select,textarea,a,[tabindex]'))target.setAttribute('tabindex','-1')}catch{}q('dpro-target-status').className='dpro-target-status ok';q('dpro-target-status').textContent=found.kind==='primary'?'対象を確認できました':'安全な代替対象で案内しています';scheduleHighlight();return}tries++;if(tries<60)setTimeout(run,150);else{q('dpro-target-status').className='dpro-target-status warn';q('dpro-target-status').textContent='対象が表示されません。画面を確認して次へ進んでください。';clearHighlight()}};setTimeout(run,30)}
function targetRect(){if(!target||!visible(target))return null;const ir=frame.getBoundingClientRect(),r=target.getBoundingClientRect();return{left:ir.left+r.left,top:ir.top+r.top,width:r.width,height:r.height,right:ir.left+r.right,bottom:ir.top+r.bottom}}
function scheduleHighlight(){cancelAnimationFrame(raf);const loop=()=>{if(!card.classList.contains('is-open'))return;const r=targetRect();if(r){const pad=6;highlight.style.left=`${Math.max(0,r.left-pad)}px`;highlight.style.top=`${Math.max(0,r.top-pad)}px`;highlight.style.width=`${Math.max(8,Math.min(innerWidth-Math.max(0,r.left-pad),r.width+pad*2))}px`;highlight.style.height=`${Math.max(8,Math.min(innerHeight-Math.max(0,r.top-pad),r.height+pad*2))}px`;highlight.classList.add('is-visible')}else highlight.classList.remove('is-visible');raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop)}
function clearHighlight(){cancelAnimationFrame(raf);highlight.classList.remove('is-visible')}
function clamp(x,y){const r=card.getBoundingClientRect(),margin=8;const maxX=Math.max(margin,innerWidth-r.width-margin),maxY=Math.max(margin,innerHeight-r.height-margin);return{x:Math.min(maxX,Math.max(margin,Number(x)||margin)),y:Math.min(maxY,Math.max(margin,Number(y)||margin))}}
function applyCardPosition(x,y,save=false){const p=clamp(x,y);card.style.left=`${p.x}px`;card.style.top=`${p.y}px`;if(save)saveState({x:p.x,y:p.y});return p}
function dragStart(e){if(e.target.closest('button,input,select,textarea,a'))return;const p=applyCardPosition(state.x,state.y);drag={id:e.pointerId,startX:e.clientX,startY:e.clientY,x:p.x,y:p.y};q('dpro-drag-handle').classList.add('is-dragging');try{q('dpro-drag-handle').setPointerCapture(e.pointerId)}catch{}e.preventDefault()}
function dragMove(e){if(!drag||e.pointerId!==drag.id)return;applyCardPosition(drag.x+(e.clientX-drag.startX),drag.y+(e.clientY-drag.startY));e.preventDefault()}
function dragEnd(e){if(!drag||e.pointerId!==drag.id)return;const p=clamp(parseFloat(card.style.left),parseFloat(card.style.top));saveState({x:p.x,y:p.y});q('dpro-drag-handle').classList.remove('is-dragging');drag=null}
function focusTarget(){try{target?.focus({preventScroll:true})}catch{}}
function testResolve(primary,fallback){const doc=frameDoc();if(!doc)return null;const found=findTargetIn(doc,primary,fallback);return found?{selector:found.selector,kind:found.kind}:null}
function snapshot(){const cr=card.getBoundingClientRect(),hr=highlight.getBoundingClientRect(),doc=frameDoc();return{version:VERSION,status:state.status,step:state.step+1,stepIndex:state.step,first10Count:STEPS.length,route:current().route,frameRoute:(frame.getAttribute('src')||''),targetSelector,targetResolved:!!target&&visible(target),card:{left:cr.left,top:cr.top,right:cr.right,bottom:cr.bottom,width:cr.width,height:cr.height,visible:card.classList.contains('is-open')},highlight:{left:hr.left,top:hr.top,right:hr.right,bottom:hr.bottom,width:hr.width,height:hr.height,visible:highlight.classList.contains('is-visible')},outer:{innerWidth,innerHeight,docScrollWidth:document.documentElement.scrollWidth,bodyScrollWidth:document.body.scrollWidth},frame:doc?{innerWidth:frame.contentWindow.innerWidth,innerHeight:frame.contentWindow.innerHeight,docScrollWidth:doc.documentElement.scrollWidth,bodyScrollWidth:doc.body?.scrollWidth||0}:null}}
q('dpro-start').addEventListener('click',start);q('dpro-resume').addEventListener('click',resume);q('dpro-replay').addEventListener('click',replay);q('dpro-next').addEventListener('click',next);q('dpro-back').addEventListener('click',back);q('dpro-close').addEventListener('click',closeTutorial);q('dpro-skip').addEventListener('click',skip);q('dpro-dock').addEventListener('click',resume);q('dpro-finish-replay').addEventListener('click',replay);q('dpro-finish-close').addEventListener('click',showLauncher);
const handle=q('dpro-drag-handle');handle.addEventListener('pointerdown',dragStart);handle.addEventListener('pointermove',dragMove);handle.addEventListener('pointerup',dragEnd);handle.addEventListener('pointercancel',dragEnd);
frame.addEventListener('load',resolveTargetSoon);window.addEventListener('resize',()=>applyCardPosition(parseFloat(card.style.left)||state.x,parseFloat(card.style.top)||state.y,true));window.addEventListener('keydown',e=>{if(!card.classList.contains('is-open'))return;if(e.key==='Escape'){e.preventDefault();closeTutorial()}else if(e.key==='ArrowRight'){e.preventDefault();next()}else if(e.key==='ArrowLeft'){e.preventDefault();back()}else if(e.key==='F6'){e.preventDefault();focusTarget()}});
window.DPRO_TUTORIAL_QA={VERSION,STEPS:Object.freeze(STEPS.map(x=>({...x}))),snapshot,start,resume,replay,next,back,skip,close:closeTutorial,focusTarget,testResolve,reset:()=>{localStorage.removeItem(KEY);state=defaultState();showLauncher()}};
applyCardPosition(state.x,state.y);showLauncher();
if(new URLSearchParams(location.search).get('qa')==='1')setTimeout(start,50);
})();